### PR TITLE
for making orhtomcl work with latest mysql

### PR DESCRIPTION
**Pull request by aseetharam**

### CODE REVIEW

**Comment by aseetharam** [comment]
Based on this thread https://www.biostars.org/p/47418/ you need to add that string to make it work!

**Comment by rgrandin** [comment]
Interesting.  Did it not work for you as-is?


The MySQL container is running MySQL 5.7.21.  I don't remember offhand what version is in the OrthoMCL container, but it seemed to work for me.

________________________________

**Review by rgrandin — APPROVED** [review]
I'm not sure this was necessary when using my containers, but the containers seem to still work with this updated connection string.

**Comment by aseetharam** [comment]
Nope, when I tried it, I got this error:
```
Singularity orthomcl.simg:~/arnstrm/usda/ncbi-genomes-2018-04-12/pep> orthomclLoadBlast orthomcl.config similarSequences.txt
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
        LANGUAGE = (unset),
        LC_ALL = (unset),
        LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
DBD::mysql::st execute failed: The used command is not allowed with this MySQL version at /software/orthomclSoftware-v2.0.9/bin/orthomclLoadBlast line 39, <F> line 12.
```
But adding that line, fixed the issue.

**Comment by rgrandin** [comment]
Is the 2nd argument causing an issue?  Here's output on my box showing that the original form works:

```
Singularity orthomcl.simg:/data/scratch/tmp> orthomclInstallSchema orthomcl.config2
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
        LANGUAGE = "en_US.UTF-8",
        LC_ALL = "en_US.UTF-8",
        LC_PAPER = "en_US.UTF-8",
        LC_ADDRESS = "en_US.UTF-8",
        LC_MONETARY = "en_US.UTF-8",
        LC_NUMERIC = "en_US.UTF-8",
        LC_TELEPHONE = "en_US.UTF-8",
        LC_MESSAGES = "en_US.UTF-8",
        LC_IDENTIFICATION = "en_US.UTF-8",
        LC_COLLATE = "en_US.UTF-8",
        LC_MEASUREMENT = "en_US.UTF-8",
        LC_CTYPE = "en_US.UTF-8",
        LC_TIME = "en_US.UTF-8",
        LC_NAME = "en_US.UTF-8",
        LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").

Singularity orthomcl.simg:/data/scratch/tmp> cat orthomcl.config2
dbVendor=mysql
dbConnectString=dbi:mysql:orthomcl:localhost
dbLogin=root
dbPassword=my-secret-pw
similarSequencesTable=SimilarSequences
orthologTable=Ortholog
inParalogTable=InParalog
coOrthologTable=CoOrtholog
interTaxonMatchView=InterTaxonMatch
percentMatchCutoff=50
evalueExponentCutoff=-5
oracleIndexTblSpc=NONE

Singularity orthomcl.simg:/data/scratch/tmp> mysql --version
mysql  Ver 14.14 Distrib 5.6.30, for debian-linux-gnu (x86_64) using  EditLine wrapper
```

**Comment by aseetharam** [comment]
the `orthomclInstallSchema` works that way, but when you try to load data to the table (`orthomclLoadBlast `) is when you get the error.

**Comment by rgrandin** [comment]
Fun.  It's always nice when the commands don't behave consistently.  Looks like that biostars thread is incomplete with their MySQL version info since both the server and client in this case is v5.6+.

Thanks for catching this!

**Pull request merged**
